global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'post-analyzer-monitor'

scrape_configs:
  - job_name: 'gateway'
    static_configs:
      - targets: ['gateway:8080']
    metrics_path: '/metrics'
    scrape_interval: 10s

  - job_name: 'postsvc'
    static_configs:
      - targets: ['postsvc:9011']
    metrics_path: '/metrics'
    scrape_interval: 10s

  - job_name: 'authsvc'
    static_configs:
      - targets: ['authsvc:9012']
    metrics_path: '/metrics'
    scrape_interval: 10s

  - job_name: 'analytics-consumer'
    static_configs:
      - targets: ['analytics-consumer:9101']
    metrics_path: '/metrics'
    scrape_interval: 10s

  - job_name: 'reanalysis-worker'
    static_configs:
      - targets: ['reanalysis-worker:9102']
    metrics_path: '/metrics'
    scrape_interval: 10s

  - job_name: 'notification-consumer'
    static_configs:
      - targets: ['notification-consumer:9103']
    metrics_path: '/metrics'
    scrape_interval: 10s
