// Code generated by thriftgo (0.4.5). DO NOT EDIT.

package auth

import (
	"Post_Analyzer_Webserver/kitex_gen/base"
	"context"
	"fmt"
)

type Subject struct {
	UserId     int64             `thrift:"UserId,1" frugal:"1,default,i64" json:"UserId"`
	Username   string            `thrift:"Username,2" frugal:"2,default,string" json:"Username"`
	Role       string            `thrift:"Role,3" frugal:"3,default,string" json:"Role"`
	Attributes map[string]string `thrift:"Attributes,4" frugal:"4,default,map<string:string>" json:"Attributes"`
}

func NewSubject() *Subject {
	return &Subject{}
}

func (p *Subject) InitDefault() {
}

func (p *Subject) GetUserId() (v int64) {
	return p.UserId
}

func (p *Subject) GetUsername() (v string) {
	return p.Username
}

func (p *Subject) GetRole() (v string) {
	return p.Role
}

func (p *Subject) GetAttributes() (v map[string]string) {
	return p.Attributes
}
func (p *Subject) SetUserId(val int64) {
	p.UserId = val
}
func (p *Subject) SetUsername(val string) {
	p.Username = val
}
func (p *Subject) SetRole(val string) {
	p.Role = val
}
func (p *Subject) SetAttributes(val map[string]string) {
	p.Attributes = val
}

func (p *Subject) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("Subject(%+v)", *p)
}

var fieldIDToName_Subject = map[int16]string{
	1: "UserId",
	2: "Username",
	3: "Role",
	4: "Attributes",
}

type LoginRequest struct {
	Base     *base.Base `thrift:"Base,1" frugal:"1,default,base.Base" json:"Base"`
	Username string     `thrift:"Username,2" frugal:"2,default,string" json:"Username"`
	Password string     `thrift:"Password,3" frugal:"3,default,string" json:"Password"`
}

func NewLoginRequest() *LoginRequest {
	return &LoginRequest{}
}

func (p *LoginRequest) InitDefault() {
}

var LoginRequest_Base_DEFAULT *base.Base

func (p *LoginRequest) GetBase() (v *base.Base) {
	if !p.IsSetBase() {
		return LoginRequest_Base_DEFAULT
	}
	return p.Base
}

func (p *LoginRequest) GetUsername() (v string) {
	return p.Username
}

func (p *LoginRequest) GetPassword() (v string) {
	return p.Password
}
func (p *LoginRequest) SetBase(val *base.Base) {
	p.Base = val
}
func (p *LoginRequest) SetUsername(val string) {
	p.Username = val
}
func (p *LoginRequest) SetPassword(val string) {
	p.Password = val
}

func (p *LoginRequest) IsSetBase() bool {
	return p.Base != nil
}

func (p *LoginRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("LoginRequest(%+v)", *p)
}

var fieldIDToName_LoginRequest = map[int16]string{
	1: "Base",
	2: "Username",
	3: "Password",
}

type LoginResponse struct {
	Token     string         `thrift:"Token,1" frugal:"1,default,string" json:"Token"`
	ExpiresAt int64          `thrift:"ExpiresAt,2" frugal:"2,default,i64" json:"ExpiresAt"`
	Subject   *Subject       `thrift:"Subject,3" frugal:"3,default,Subject" json:"Subject"`
	BaseResp  *base.BaseResp `thrift:"BaseResp,255" frugal:"255,default,base.BaseResp" json:"BaseResp"`
}

func NewLoginResponse() *LoginResponse {
	return &LoginResponse{}
}

func (p *LoginResponse) InitDefault() {
}

func (p *LoginResponse) GetToken() (v string) {
	return p.Token
}

func (p *LoginResponse) GetExpiresAt() (v int64) {
	return p.ExpiresAt
}

var LoginResponse_Subject_DEFAULT *Subject

func (p *LoginResponse) GetSubject() (v *Subject) {
	if !p.IsSetSubject() {
		return LoginResponse_Subject_DEFAULT
	}
	return p.Subject
}

var LoginResponse_BaseResp_DEFAULT *base.BaseResp

func (p *LoginResponse) GetBaseResp() (v *base.BaseResp) {
	if !p.IsSetBaseResp() {
		return LoginResponse_BaseResp_DEFAULT
	}
	return p.BaseResp
}
func (p *LoginResponse) SetToken(val string) {
	p.Token = val
}
func (p *LoginResponse) SetExpiresAt(val int64) {
	p.ExpiresAt = val
}
func (p *LoginResponse) SetSubject(val *Subject) {
	p.Subject = val
}
func (p *LoginResponse) SetBaseResp(val *base.BaseResp) {
	p.BaseResp = val
}

func (p *LoginResponse) IsSetSubject() bool {
	return p.Subject != nil
}

func (p *LoginResponse) IsSetBaseResp() bool {
	return p.BaseResp != nil
}

func (p *LoginResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("LoginResponse(%+v)", *p)
}

var fieldIDToName_LoginResponse = map[int16]string{
	1:   "Token",
	2:   "ExpiresAt",
	3:   "Subject",
	255: "BaseResp",
}

type ValidateTokenRequest struct {
	Base  *base.Base `thrift:"Base,1" frugal:"1,default,base.Base" json:"Base"`
	Token string     `thrift:"Token,2" frugal:"2,default,string" json:"Token"`
}

func NewValidateTokenRequest() *ValidateTokenRequest {
	return &ValidateTokenRequest{}
}

func (p *ValidateTokenRequest) InitDefault() {
}

var ValidateTokenRequest_Base_DEFAULT *base.Base

func (p *ValidateTokenRequest) GetBase() (v *base.Base) {
	if !p.IsSetBase() {
		return ValidateTokenRequest_Base_DEFAULT
	}
	return p.Base
}

func (p *ValidateTokenRequest) GetToken() (v string) {
	return p.Token
}
func (p *ValidateTokenRequest) SetBase(val *base.Base) {
	p.Base = val
}
func (p *ValidateTokenRequest) SetToken(val string) {
	p.Token = val
}

func (p *ValidateTokenRequest) IsSetBase() bool {
	return p.Base != nil
}

func (p *ValidateTokenRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ValidateTokenRequest(%+v)", *p)
}

var fieldIDToName_ValidateTokenRequest = map[int16]string{
	1: "Base",
	2: "Token",
}

type ValidateTokenResponse struct {
	Valid    bool           `thrift:"Valid,1" frugal:"1,default,bool" json:"Valid"`
	Subject  *Subject       `thrift:"Subject,2" frugal:"2,default,Subject" json:"Subject"`
	BaseResp *base.BaseResp `thrift:"BaseResp,255" frugal:"255,default,base.BaseResp" json:"BaseResp"`
}

func NewValidateTokenResponse() *ValidateTokenResponse {
	return &ValidateTokenResponse{}
}

func (p *ValidateTokenResponse) InitDefault() {
}

func (p *ValidateTokenResponse) GetValid() (v bool) {
	return p.Valid
}

var ValidateTokenResponse_Subject_DEFAULT *Subject

func (p *ValidateTokenResponse) GetSubject() (v *Subject) {
	if !p.IsSetSubject() {
		return ValidateTokenResponse_Subject_DEFAULT
	}
	return p.Subject
}

var ValidateTokenResponse_BaseResp_DEFAULT *base.BaseResp

func (p *ValidateTokenResponse) GetBaseResp() (v *base.BaseResp) {
	if !p.IsSetBaseResp() {
		return ValidateTokenResponse_BaseResp_DEFAULT
	}
	return p.BaseResp
}
func (p *ValidateTokenResponse) SetValid(val bool) {
	p.Valid = val
}
func (p *ValidateTokenResponse) SetSubject(val *Subject) {
	p.Subject = val
}
func (p *ValidateTokenResponse) SetBaseResp(val *base.BaseResp) {
	p.BaseResp = val
}

func (p *ValidateTokenResponse) IsSetSubject() bool {
	return p.Subject != nil
}

func (p *ValidateTokenResponse) IsSetBaseResp() bool {
	return p.BaseResp != nil
}

func (p *ValidateTokenResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ValidateTokenResponse(%+v)", *p)
}

var fieldIDToName_ValidateTokenResponse = map[int16]string{
	1:   "Valid",
	2:   "Subject",
	255: "BaseResp",
}

type AuthorizeRequest struct {
	Base               *base.Base        `thrift:"Base,1" frugal:"1,default,base.Base" json:"Base"`
	Subject            *Subject          `thrift:"Subject,2" frugal:"2,default,Subject" json:"Subject"`
	Resource           string            `thrift:"Resource,3" frugal:"3,default,string" json:"Resource"`
	Action             string            `thrift:"Action,4" frugal:"4,default,string" json:"Action"`
	ResourceAttributes map[string]string `thrift:"ResourceAttributes,5,optional" frugal:"5,optional,map<string:string>" json:"ResourceAttributes,omitempty"`
	Context            map[string]string `thrift:"Context,6,optional" frugal:"6,optional,map<string:string>" json:"Context,omitempty"`
}

func NewAuthorizeRequest() *AuthorizeRequest {
	return &AuthorizeRequest{}
}

func (p *AuthorizeRequest) InitDefault() {
}

var AuthorizeRequest_Base_DEFAULT *base.Base

func (p *AuthorizeRequest) GetBase() (v *base.Base) {
	if !p.IsSetBase() {
		return AuthorizeRequest_Base_DEFAULT
	}
	return p.Base
}

var AuthorizeRequest_Subject_DEFAULT *Subject

func (p *AuthorizeRequest) GetSubject() (v *Subject) {
	if !p.IsSetSubject() {
		return AuthorizeRequest_Subject_DEFAULT
	}
	return p.Subject
}

func (p *AuthorizeRequest) GetResource() (v string) {
	return p.Resource
}

func (p *AuthorizeRequest) GetAction() (v string) {
	return p.Action
}

var AuthorizeRequest_ResourceAttributes_DEFAULT map[string]string

func (p *AuthorizeRequest) GetResourceAttributes() (v map[string]string) {
	if !p.IsSetResourceAttributes() {
		return AuthorizeRequest_ResourceAttributes_DEFAULT
	}
	return p.ResourceAttributes
}

var AuthorizeRequest_Context_DEFAULT map[string]string

func (p *AuthorizeRequest) GetContext() (v map[string]string) {
	if !p.IsSetContext() {
		return AuthorizeRequest_Context_DEFAULT
	}
	return p.Context
}
func (p *AuthorizeRequest) SetBase(val *base.Base) {
	p.Base = val
}
func (p *AuthorizeRequest) SetSubject(val *Subject) {
	p.Subject = val
}
func (p *AuthorizeRequest) SetResource(val string) {
	p.Resource = val
}
func (p *AuthorizeRequest) SetAction(val string) {
	p.Action = val
}
func (p *AuthorizeRequest) SetResourceAttributes(val map[string]string) {
	p.ResourceAttributes = val
}
func (p *AuthorizeRequest) SetContext(val map[string]string) {
	p.Context = val
}

func (p *AuthorizeRequest) IsSetBase() bool {
	return p.Base != nil
}

func (p *AuthorizeRequest) IsSetSubject() bool {
	return p.Subject != nil
}

func (p *AuthorizeRequest) IsSetResourceAttributes() bool {
	return p.ResourceAttributes != nil
}

func (p *AuthorizeRequest) IsSetContext() bool {
	return p.Context != nil
}

func (p *AuthorizeRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("AuthorizeRequest(%+v)", *p)
}

var fieldIDToName_AuthorizeRequest = map[int16]string{
	1: "Base",
	2: "Subject",
	3: "Resource",
	4: "Action",
	5: "ResourceAttributes",
	6: "Context",
}

type AuthorizeResponse struct {
	Allowed       bool           `thrift:"Allowed,1" frugal:"1,default,bool" json:"Allowed"`
	Reason        string         `thrift:"Reason,2" frugal:"2,default,string" json:"Reason"`
	MatchedPolicy string         `thrift:"MatchedPolicy,3" frugal:"3,default,string" json:"MatchedPolicy"`
	BaseResp      *base.BaseResp `thrift:"BaseResp,255" frugal:"255,default,base.BaseResp" json:"BaseResp"`
}

func NewAuthorizeResponse() *AuthorizeResponse {
	return &AuthorizeResponse{}
}

func (p *AuthorizeResponse) InitDefault() {
}

func (p *AuthorizeResponse) GetAllowed() (v bool) {
	return p.Allowed
}

func (p *AuthorizeResponse) GetReason() (v string) {
	return p.Reason
}

func (p *AuthorizeResponse) GetMatchedPolicy() (v string) {
	return p.MatchedPolicy
}

var AuthorizeResponse_BaseResp_DEFAULT *base.BaseResp

func (p *AuthorizeResponse) GetBaseResp() (v *base.BaseResp) {
	if !p.IsSetBaseResp() {
		return AuthorizeResponse_BaseResp_DEFAULT
	}
	return p.BaseResp
}
func (p *AuthorizeResponse) SetAllowed(val bool) {
	p.Allowed = val
}
func (p *AuthorizeResponse) SetReason(val string) {
	p.Reason = val
}
func (p *AuthorizeResponse) SetMatchedPolicy(val string) {
	p.MatchedPolicy = val
}
func (p *AuthorizeResponse) SetBaseResp(val *base.BaseResp) {
	p.BaseResp = val
}

func (p *AuthorizeResponse) IsSetBaseResp() bool {
	return p.BaseResp != nil
}

func (p *AuthorizeResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("AuthorizeResponse(%+v)", *p)
}

var fieldIDToName_AuthorizeResponse = map[int16]string{
	1:   "Allowed",
	2:   "Reason",
	3:   "MatchedPolicy",
	255: "BaseResp",
}

type AuthService interface {
	Login(ctx context.Context, req *LoginRequest) (r *LoginResponse, err error)

	ValidateToken(ctx context.Context, req *ValidateTokenRequest) (r *ValidateTokenResponse, err error)

	Authorize(ctx context.Context, req *AuthorizeRequest) (r *AuthorizeResponse, err error)
}

type AuthServiceLoginArgs struct {
	Req *LoginRequest `thrift:"req,1" frugal:"1,default,LoginRequest" json:"req"`
}

func NewAuthServiceLoginArgs() *AuthServiceLoginArgs {
	return &AuthServiceLoginArgs{}
}

func (p *AuthServiceLoginArgs) InitDefault() {
}

var AuthServiceLoginArgs_Req_DEFAULT *LoginRequest

func (p *AuthServiceLoginArgs) GetReq() (v *LoginRequest) {
	if !p.IsSetReq() {
		return AuthServiceLoginArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *AuthServiceLoginArgs) SetReq(val *LoginRequest) {
	p.Req = val
}

func (p *AuthServiceLoginArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *AuthServiceLoginArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("AuthServiceLoginArgs(%+v)", *p)
}

var fieldIDToName_AuthServiceLoginArgs = map[int16]string{
	1: "req",
}

type AuthServiceLoginResult struct {
	Success *LoginResponse `thrift:"success,0,optional" frugal:"0,optional,LoginResponse" json:"success,omitempty"`
}

func NewAuthServiceLoginResult() *AuthServiceLoginResult {
	return &AuthServiceLoginResult{}
}

func (p *AuthServiceLoginResult) InitDefault() {
}

var AuthServiceLoginResult_Success_DEFAULT *LoginResponse

func (p *AuthServiceLoginResult) GetSuccess() (v *LoginResponse) {
	if !p.IsSetSuccess() {
		return AuthServiceLoginResult_Success_DEFAULT
	}
	return p.Success
}
func (p *AuthServiceLoginResult) SetSuccess(x interface{}) {
	p.Success = x.(*LoginResponse)
}

func (p *AuthServiceLoginResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *AuthServiceLoginResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("AuthServiceLoginResult(%+v)", *p)
}

var fieldIDToName_AuthServiceLoginResult = map[int16]string{
	0: "success",
}

type AuthServiceValidateTokenArgs struct {
	Req *ValidateTokenRequest `thrift:"req,1" frugal:"1,default,ValidateTokenRequest" json:"req"`
}

func NewAuthServiceValidateTokenArgs() *AuthServiceValidateTokenArgs {
	return &AuthServiceValidateTokenArgs{}
}

func (p *AuthServiceValidateTokenArgs) InitDefault() {
}

var AuthServiceValidateTokenArgs_Req_DEFAULT *ValidateTokenRequest

func (p *AuthServiceValidateTokenArgs) GetReq() (v *ValidateTokenRequest) {
	if !p.IsSetReq() {
		return AuthServiceValidateTokenArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *AuthServiceValidateTokenArgs) SetReq(val *ValidateTokenRequest) {
	p.Req = val
}

func (p *AuthServiceValidateTokenArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *AuthServiceValidateTokenArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("AuthServiceValidateTokenArgs(%+v)", *p)
}

var fieldIDToName_AuthServiceValidateTokenArgs = map[int16]string{
	1: "req",
}

type AuthServiceValidateTokenResult struct {
	Success *ValidateTokenResponse `thrift:"success,0,optional" frugal:"0,optional,ValidateTokenResponse" json:"success,omitempty"`
}

func NewAuthServiceValidateTokenResult() *AuthServiceValidateTokenResult {
	return &AuthServiceValidateTokenResult{}
}

func (p *AuthServiceValidateTokenResult) InitDefault() {
}

var AuthServiceValidateTokenResult_Success_DEFAULT *ValidateTokenResponse

func (p *AuthServiceValidateTokenResult) GetSuccess() (v *ValidateTokenResponse) {
	if !p.IsSetSuccess() {
		return AuthServiceValidateTokenResult_Success_DEFAULT
	}
	return p.Success
}
func (p *AuthServiceValidateTokenResult) SetSuccess(x interface{}) {
	p.Success = x.(*ValidateTokenResponse)
}

func (p *AuthServiceValidateTokenResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *AuthServiceValidateTokenResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("AuthServiceValidateTokenResult(%+v)", *p)
}

var fieldIDToName_AuthServiceValidateTokenResult = map[int16]string{
	0: "success",
}

type AuthServiceAuthorizeArgs struct {
	Req *AuthorizeRequest `thrift:"req,1" frugal:"1,default,AuthorizeRequest" json:"req"`
}

func NewAuthServiceAuthorizeArgs() *AuthServiceAuthorizeArgs {
	return &AuthServiceAuthorizeArgs{}
}

func (p *AuthServiceAuthorizeArgs) InitDefault() {
}

var AuthServiceAuthorizeArgs_Req_DEFAULT *AuthorizeRequest

func (p *AuthServiceAuthorizeArgs) GetReq() (v *AuthorizeRequest) {
	if !p.IsSetReq() {
		return AuthServiceAuthorizeArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *AuthServiceAuthorizeArgs) SetReq(val *AuthorizeRequest) {
	p.Req = val
}

func (p *AuthServiceAuthorizeArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *AuthServiceAuthorizeArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("AuthServiceAuthorizeArgs(%+v)", *p)
}

var fieldIDToName_AuthServiceAuthorizeArgs = map[int16]string{
	1: "req",
}

type AuthServiceAuthorizeResult struct {
	Success *AuthorizeResponse `thrift:"success,0,optional" frugal:"0,optional,AuthorizeResponse" json:"success,omitempty"`
}

func NewAuthServiceAuthorizeResult() *AuthServiceAuthorizeResult {
	return &AuthServiceAuthorizeResult{}
}

func (p *AuthServiceAuthorizeResult) InitDefault() {
}

var AuthServiceAuthorizeResult_Success_DEFAULT *AuthorizeResponse

func (p *AuthServiceAuthorizeResult) GetSuccess() (v *AuthorizeResponse) {
	if !p.IsSetSuccess() {
		return AuthServiceAuthorizeResult_Success_DEFAULT
	}
	return p.Success
}
func (p *AuthServiceAuthorizeResult) SetSuccess(x interface{}) {
	p.Success = x.(*AuthorizeResponse)
}

func (p *AuthServiceAuthorizeResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *AuthServiceAuthorizeResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("AuthServiceAuthorizeResult(%+v)", *p)
}

var fieldIDToName_AuthServiceAuthorizeResult = map[int16]string{
	0: "success",
}
