// Code generated by Kitex v0.16.3. DO NOT EDIT.

package postservice

import (
	post "Post_Analyzer_Webserver/kitex_gen/post"
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	ListPosts(ctx context.Context, req *post.ListPostsRequest, callOptions ...callopt.Option) (r *post.ListPostsResponse, err error)
	GetPost(ctx context.Context, req *post.GetPostRequest, callOptions ...callopt.Option) (r *post.GetPostResponse, err error)
	CreatePost(ctx context.Context, req *post.CreatePostRequest, callOptions ...callopt.Option) (r *post.CreatePostResponse, err error)
	UpdatePost(ctx context.Context, req *post.UpdatePostRequest, callOptions ...callopt.Option) (r *post.UpdatePostResponse, err error)
	DeletePost(ctx context.Context, req *post.DeletePostRequest, callOptions ...callopt.Option) (r *post.DeletePostResponse, err error)
	BatchCreatePosts(ctx context.Context, req *post.BatchCreatePostsRequest, callOptions ...callopt.Option) (r *post.BatchCreatePostsResponse, err error)
	AnalyzePosts(ctx context.Context, req *post.AnalyzePostsRequest, callOptions ...callopt.Option) (r *post.AnalyzePostsResponse, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfoForClient(), options...)
	if err != nil {
		return nil, err
	}
	return &kPostServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kPostServiceClient struct {
	*kClient
}

func (p *kPostServiceClient) ListPosts(ctx context.Context, req *post.ListPostsRequest, callOptions ...callopt.Option) (r *post.ListPostsResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ListPosts(ctx, req)
}

func (p *kPostServiceClient) GetPost(ctx context.Context, req *post.GetPostRequest, callOptions ...callopt.Option) (r *post.GetPostResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetPost(ctx, req)
}

func (p *kPostServiceClient) CreatePost(ctx context.Context, req *post.CreatePostRequest, callOptions ...callopt.Option) (r *post.CreatePostResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CreatePost(ctx, req)
}

func (p *kPostServiceClient) UpdatePost(ctx context.Context, req *post.UpdatePostRequest, callOptions ...callopt.Option) (r *post.UpdatePostResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.UpdatePost(ctx, req)
}

func (p *kPostServiceClient) DeletePost(ctx context.Context, req *post.DeletePostRequest, callOptions ...callopt.Option) (r *post.DeletePostResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.DeletePost(ctx, req)
}

func (p *kPostServiceClient) BatchCreatePosts(ctx context.Context, req *post.BatchCreatePostsRequest, callOptions ...callopt.Option) (r *post.BatchCreatePostsResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.BatchCreatePosts(ctx, req)
}

func (p *kPostServiceClient) AnalyzePosts(ctx context.Context, req *post.AnalyzePostsRequest, callOptions ...callopt.Option) (r *post.AnalyzePostsResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.AnalyzePosts(ctx, req)
}
