// Code generated by Kitex v0.16.3. DO NOT EDIT.

package postservice

import (
	post "Post_Analyzer_Webserver/kitex_gen/post"
	"context"
	"errors"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"ListPosts": kitex.NewMethodInfo(
		listPostsHandler,
		newPostServiceListPostsArgs,
		newPostServiceListPostsResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"GetPost": kitex.NewMethodInfo(
		getPostHandler,
		newPostServiceGetPostArgs,
		newPostServiceGetPostResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"CreatePost": kitex.NewMethodInfo(
		createPostHandler,
		newPostServiceCreatePostArgs,
		newPostServiceCreatePostResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"UpdatePost": kitex.NewMethodInfo(
		updatePostHandler,
		newPostServiceUpdatePostArgs,
		newPostServiceUpdatePostResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"DeletePost": kitex.NewMethodInfo(
		deletePostHandler,
		newPostServiceDeletePostArgs,
		newPostServiceDeletePostResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"BatchCreatePosts": kitex.NewMethodInfo(
		batchCreatePostsHandler,
		newPostServiceBatchCreatePostsArgs,
		newPostServiceBatchCreatePostsResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"AnalyzePosts": kitex.NewMethodInfo(
		analyzePostsHandler,
		newPostServiceAnalyzePostsArgs,
		newPostServiceAnalyzePostsResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
}

var (
	postServiceServiceInfo                = NewServiceInfo()
	postServiceServiceInfoForClient       = NewServiceInfoForClient()
	postServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return postServiceServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return postServiceServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return postServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "PostService"
	handlerType := (*post.PostService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "post",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.16.3",
		Extra:           extra,
	}
	return svcInfo
}

func listPostsHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*post.PostServiceListPostsArgs)
	realResult := result.(*post.PostServiceListPostsResult)
	success, err := handler.(post.PostService).ListPosts(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newPostServiceListPostsArgs() interface{} {
	return post.NewPostServiceListPostsArgs()
}

func newPostServiceListPostsResult() interface{} {
	return post.NewPostServiceListPostsResult()
}

func getPostHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*post.PostServiceGetPostArgs)
	realResult := result.(*post.PostServiceGetPostResult)
	success, err := handler.(post.PostService).GetPost(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newPostServiceGetPostArgs() interface{} {
	return post.NewPostServiceGetPostArgs()
}

func newPostServiceGetPostResult() interface{} {
	return post.NewPostServiceGetPostResult()
}

func createPostHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*post.PostServiceCreatePostArgs)
	realResult := result.(*post.PostServiceCreatePostResult)
	success, err := handler.(post.PostService).CreatePost(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newPostServiceCreatePostArgs() interface{} {
	return post.NewPostServiceCreatePostArgs()
}

func newPostServiceCreatePostResult() interface{} {
	return post.NewPostServiceCreatePostResult()
}

func updatePostHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*post.PostServiceUpdatePostArgs)
	realResult := result.(*post.PostServiceUpdatePostResult)
	success, err := handler.(post.PostService).UpdatePost(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newPostServiceUpdatePostArgs() interface{} {
	return post.NewPostServiceUpdatePostArgs()
}

func newPostServiceUpdatePostResult() interface{} {
	return post.NewPostServiceUpdatePostResult()
}

func deletePostHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*post.PostServiceDeletePostArgs)
	realResult := result.(*post.PostServiceDeletePostResult)
	success, err := handler.(post.PostService).DeletePost(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newPostServiceDeletePostArgs() interface{} {
	return post.NewPostServiceDeletePostArgs()
}

func newPostServiceDeletePostResult() interface{} {
	return post.NewPostServiceDeletePostResult()
}

func batchCreatePostsHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*post.PostServiceBatchCreatePostsArgs)
	realResult := result.(*post.PostServiceBatchCreatePostsResult)
	success, err := handler.(post.PostService).BatchCreatePosts(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newPostServiceBatchCreatePostsArgs() interface{} {
	return post.NewPostServiceBatchCreatePostsArgs()
}

func newPostServiceBatchCreatePostsResult() interface{} {
	return post.NewPostServiceBatchCreatePostsResult()
}

func analyzePostsHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*post.PostServiceAnalyzePostsArgs)
	realResult := result.(*post.PostServiceAnalyzePostsResult)
	success, err := handler.(post.PostService).AnalyzePosts(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newPostServiceAnalyzePostsArgs() interface{} {
	return post.NewPostServiceAnalyzePostsArgs()
}

func newPostServiceAnalyzePostsResult() interface{} {
	return post.NewPostServiceAnalyzePostsResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) ListPosts(ctx context.Context, req *post.ListPostsRequest) (r *post.ListPostsResponse, err error) {
	var _args post.PostServiceListPostsArgs
	_args.Req = req
	var _result post.PostServiceListPostsResult
	if err = p.c.Call(ctx, "ListPosts", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetPost(ctx context.Context, req *post.GetPostRequest) (r *post.GetPostResponse, err error) {
	var _args post.PostServiceGetPostArgs
	_args.Req = req
	var _result post.PostServiceGetPostResult
	if err = p.c.Call(ctx, "GetPost", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) CreatePost(ctx context.Context, req *post.CreatePostRequest) (r *post.CreatePostResponse, err error) {
	var _args post.PostServiceCreatePostArgs
	_args.Req = req
	var _result post.PostServiceCreatePostResult
	if err = p.c.Call(ctx, "CreatePost", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) UpdatePost(ctx context.Context, req *post.UpdatePostRequest) (r *post.UpdatePostResponse, err error) {
	var _args post.PostServiceUpdatePostArgs
	_args.Req = req
	var _result post.PostServiceUpdatePostResult
	if err = p.c.Call(ctx, "UpdatePost", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) DeletePost(ctx context.Context, req *post.DeletePostRequest) (r *post.DeletePostResponse, err error) {
	var _args post.PostServiceDeletePostArgs
	_args.Req = req
	var _result post.PostServiceDeletePostResult
	if err = p.c.Call(ctx, "DeletePost", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) BatchCreatePosts(ctx context.Context, req *post.BatchCreatePostsRequest) (r *post.BatchCreatePostsResponse, err error) {
	var _args post.PostServiceBatchCreatePostsArgs
	_args.Req = req
	var _result post.PostServiceBatchCreatePostsResult
	if err = p.c.Call(ctx, "BatchCreatePosts", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) AnalyzePosts(ctx context.Context, req *post.AnalyzePostsRequest) (r *post.AnalyzePostsResponse, err error) {
	var _args post.PostServiceAnalyzePostsArgs
	_args.Req = req
	var _result post.PostServiceAnalyzePostsResult
	if err = p.c.Call(ctx, "AnalyzePosts", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
