// Code generated by Kitex v0.16.3. DO NOT EDIT.

package authservice

import (
	auth "Post_Analyzer_Webserver/kitex_gen/auth"
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	Login(ctx context.Context, req *auth.LoginRequest, callOptions ...callopt.Option) (r *auth.LoginResponse, err error)
	ValidateToken(ctx context.Context, req *auth.ValidateTokenRequest, callOptions ...callopt.Option) (r *auth.ValidateTokenResponse, err error)
	Authorize(ctx context.Context, req *auth.AuthorizeRequest, callOptions ...callopt.Option) (r *auth.AuthorizeResponse, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfoForClient(), options...)
	if err != nil {
		return nil, err
	}
	return &kAuthServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kAuthServiceClient struct {
	*kClient
}

func (p *kAuthServiceClient) Login(ctx context.Context, req *auth.LoginRequest, callOptions ...callopt.Option) (r *auth.LoginResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Login(ctx, req)
}

func (p *kAuthServiceClient) ValidateToken(ctx context.Context, req *auth.ValidateTokenRequest, callOptions ...callopt.Option) (r *auth.ValidateTokenResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ValidateToken(ctx, req)
}

func (p *kAuthServiceClient) Authorize(ctx context.Context, req *auth.AuthorizeRequest, callOptions ...callopt.Option) (r *auth.AuthorizeResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Authorize(ctx, req)
}
