apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: post-analyzer
  namespace: post-analyzer
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "1m"
spec:
  ingressClassName: nginx
  rules:
    - host: post-analyzer.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: gateway
                port: { number: 8080 }
