apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: post-analyzer

resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - postgres.yaml
  - redis.yaml
  - postsvc.yaml
  - authsvc.yaml
  - gateway.yaml
  - ingress.yaml

labels:
  - pairs:
      app.kubernetes.io/part-of: post-analyzer
    includeSelectors: false
