// Code generated by thriftgo (0.4.5). DO NOT EDIT.

package base

import (
	"fmt"
)

type Base struct {
	LogID  string            `thrift:"LogID,1" frugal:"1,default,string" json:"LogID"`
	Caller string            `thrift:"Caller,2" frugal:"2,default,string" json:"Caller"`
	Addr   string            `thrift:"Addr,3" frugal:"3,default,string" json:"Addr"`
	Client string            `thrift:"Client,4" frugal:"4,default,string" json:"Client"`
	Extra  map[string]string `thrift:"Extra,5,optional" frugal:"5,optional,map<string:string>" json:"Extra,omitempty"`
}

func NewBase() *Base {
	return &Base{
		LogID:  "",
		Caller: "",
		Addr:   "",
		Client: "",
	}
}

func (p *Base) InitDefault() {
	p.LogID = ""
	p.Caller = ""
	p.Addr = ""
	p.Client = ""
}

func (p *Base) GetLogID() (v string) {
	return p.LogID
}

func (p *Base) GetCaller() (v string) {
	return p.Caller
}

func (p *Base) GetAddr() (v string) {
	return p.Addr
}

func (p *Base) GetClient() (v string) {
	return p.Client
}

var Base_Extra_DEFAULT map[string]string

func (p *Base) GetExtra() (v map[string]string) {
	if !p.IsSetExtra() {
		return Base_Extra_DEFAULT
	}
	return p.Extra
}
func (p *Base) SetLogID(val string) {
	p.LogID = val
}
func (p *Base) SetCaller(val string) {
	p.Caller = val
}
func (p *Base) SetAddr(val string) {
	p.Addr = val
}
func (p *Base) SetClient(val string) {
	p.Client = val
}
func (p *Base) SetExtra(val map[string]string) {
	p.Extra = val
}

func (p *Base) IsSetExtra() bool {
	return p.Extra != nil
}

func (p *Base) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("Base(%+v)", *p)
}

var fieldIDToName_Base = map[int16]string{
	1: "LogID",
	2: "Caller",
	3: "Addr",
	4: "Client",
	5: "Extra",
}

type BaseResp struct {
	StatusMessage string            `thrift:"StatusMessage,1" frugal:"1,default,string" json:"StatusMessage"`
	StatusCode    int32             `thrift:"StatusCode,2" frugal:"2,default,i32" json:"StatusCode"`
	Extra         map[string]string `thrift:"Extra,3,optional" frugal:"3,optional,map<string:string>" json:"Extra,omitempty"`
}

func NewBaseResp() *BaseResp {
	return &BaseResp{
		StatusMessage: "",
		StatusCode:    0,
	}
}

func (p *BaseResp) InitDefault() {
	p.StatusMessage = ""
	p.StatusCode = 0
}

func (p *BaseResp) GetStatusMessage() (v string) {
	return p.StatusMessage
}

func (p *BaseResp) GetStatusCode() (v int32) {
	return p.StatusCode
}

var BaseResp_Extra_DEFAULT map[string]string

func (p *BaseResp) GetExtra() (v map[string]string) {
	if !p.IsSetExtra() {
		return BaseResp_Extra_DEFAULT
	}
	return p.Extra
}
func (p *BaseResp) SetStatusMessage(val string) {
	p.StatusMessage = val
}
func (p *BaseResp) SetStatusCode(val int32) {
	p.StatusCode = val
}
func (p *BaseResp) SetExtra(val map[string]string) {
	p.Extra = val
}

func (p *BaseResp) IsSetExtra() bool {
	return p.Extra != nil
}

func (p *BaseResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("BaseResp(%+v)", *p)
}

var fieldIDToName_BaseResp = map[int16]string{
	1: "StatusMessage",
	2: "StatusCode",
	3: "Extra",
}
