// Code generated by thriftgo (0.4.5). DO NOT EDIT.

package post

import (
	"Post_Analyzer_Webserver/kitex_gen/base"
	"context"
	"fmt"
)

type Post struct {
	Id        int64  `thrift:"Id,1" frugal:"1,default,i64" json:"Id"`
	UserId    int64  `thrift:"UserId,2" frugal:"2,default,i64" json:"UserId"`
	Title     string `thrift:"Title,3" frugal:"3,default,string" json:"Title"`
	Body      string `thrift:"Body,4" frugal:"4,default,string" json:"Body"`
	CreatedAt string `thrift:"CreatedAt,5" frugal:"5,default,string" json:"CreatedAt"`
	UpdatedAt string `thrift:"UpdatedAt,6" frugal:"6,default,string" json:"UpdatedAt"`
}

func NewPost() *Post {
	return &Post{}
}

func (p *Post) InitDefault() {
}

func (p *Post) GetId() (v int64) {
	return p.Id
}

func (p *Post) GetUserId() (v int64) {
	return p.UserId
}

func (p *Post) GetTitle() (v string) {
	return p.Title
}

func (p *Post) GetBody() (v string) {
	return p.Body
}

func (p *Post) GetCreatedAt() (v string) {
	return p.CreatedAt
}

func (p *Post) GetUpdatedAt() (v string) {
	return p.UpdatedAt
}
func (p *Post) SetId(val int64) {
	p.Id = val
}
func (p *Post) SetUserId(val int64) {
	p.UserId = val
}
func (p *Post) SetTitle(val string) {
	p.Title = val
}
func (p *Post) SetBody(val string) {
	p.Body = val
}
func (p *Post) SetCreatedAt(val string) {
	p.CreatedAt = val
}
func (p *Post) SetUpdatedAt(val string) {
	p.UpdatedAt = val
}

func (p *Post) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("Post(%+v)", *p)
}

var fieldIDToName_Post = map[int16]string{
	1: "Id",
	2: "UserId",
	3: "Title",
	4: "Body",
	5: "CreatedAt",
	6: "UpdatedAt",
}

type PostFilter struct {
	UserId    *int64  `thrift:"UserId,1,optional" frugal:"1,optional,i64" json:"UserId,omitempty"`
	Search    *string `thrift:"Search,2,optional" frugal:"2,optional,string" json:"Search,omitempty"`
	SortBy    *string `thrift:"SortBy,3,optional" frugal:"3,optional,string" json:"SortBy,omitempty"`
	SortOrder *string `thrift:"SortOrder,4,optional" frugal:"4,optional,string" json:"SortOrder,omitempty"`
}

func NewPostFilter() *PostFilter {
	return &PostFilter{}
}

func (p *PostFilter) InitDefault() {
}

var PostFilter_UserId_DEFAULT int64

func (p *PostFilter) GetUserId() (v int64) {
	if !p.IsSetUserId() {
		return PostFilter_UserId_DEFAULT
	}
	return *p.UserId
}

var PostFilter_Search_DEFAULT string

func (p *PostFilter) GetSearch() (v string) {
	if !p.IsSetSearch() {
		return PostFilter_Search_DEFAULT
	}
	return *p.Search
}

var PostFilter_SortBy_DEFAULT string

func (p *PostFilter) GetSortBy() (v string) {
	if !p.IsSetSortBy() {
		return PostFilter_SortBy_DEFAULT
	}
	return *p.SortBy
}

var PostFilter_SortOrder_DEFAULT string

func (p *PostFilter) GetSortOrder() (v string) {
	if !p.IsSetSortOrder() {
		return PostFilter_SortOrder_DEFAULT
	}
	return *p.SortOrder
}
func (p *PostFilter) SetUserId(val *int64) {
	p.UserId = val
}
func (p *PostFilter) SetSearch(val *string) {
	p.Search = val
}
func (p *PostFilter) SetSortBy(val *string) {
	p.SortBy = val
}
func (p *PostFilter) SetSortOrder(val *string) {
	p.SortOrder = val
}

func (p *PostFilter) IsSetUserId() bool {
	return p.UserId != nil
}

func (p *PostFilter) IsSetSearch() bool {
	return p.Search != nil
}

func (p *PostFilter) IsSetSortBy() bool {
	return p.SortBy != nil
}

func (p *PostFilter) IsSetSortOrder() bool {
	return p.SortOrder != nil
}

func (p *PostFilter) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("PostFilter(%+v)", *p)
}

var fieldIDToName_PostFilter = map[int16]string{
	1: "UserId",
	2: "Search",
	3: "SortBy",
	4: "SortOrder",
}

type Pagination struct {
	Page     int32 `thrift:"Page,1" frugal:"1,default,i32" json:"Page"`
	PageSize int32 `thrift:"PageSize,2" frugal:"2,default,i32" json:"PageSize"`
}

func NewPagination() *Pagination {
	return &Pagination{}
}

func (p *Pagination) InitDefault() {
}

func (p *Pagination) GetPage() (v int32) {
	return p.Page
}

func (p *Pagination) GetPageSize() (v int32) {
	return p.PageSize
}
func (p *Pagination) SetPage(val int32) {
	p.Page = val
}
func (p *Pagination) SetPageSize(val int32) {
	p.PageSize = val
}

func (p *Pagination) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("Pagination(%+v)", *p)
}

var fieldIDToName_Pagination = map[int16]string{
	1: "Page",
	2: "PageSize",
}

type PaginationMeta struct {
	Page       int32 `thrift:"Page,1" frugal:"1,default,i32" json:"Page"`
	PageSize   int32 `thrift:"PageSize,2" frugal:"2,default,i32" json:"PageSize"`
	TotalItems int32 `thrift:"TotalItems,3" frugal:"3,default,i32" json:"TotalItems"`
	TotalPages int32 `thrift:"TotalPages,4" frugal:"4,default,i32" json:"TotalPages"`
	HasNext    bool  `thrift:"HasNext,5" frugal:"5,default,bool" json:"HasNext"`
	HasPrev    bool  `thrift:"HasPrev,6" frugal:"6,default,bool" json:"HasPrev"`
}

func NewPaginationMeta() *PaginationMeta {
	return &PaginationMeta{}
}

func (p *PaginationMeta) InitDefault() {
}

func (p *PaginationMeta) GetPage() (v int32) {
	return p.Page
}

func (p *PaginationMeta) GetPageSize() (v int32) {
	return p.PageSize
}

func (p *PaginationMeta) GetTotalItems() (v int32) {
	return p.TotalItems
}

func (p *PaginationMeta) GetTotalPages() (v int32) {
	return p.TotalPages
}

func (p *PaginationMeta) GetHasNext() (v bool) {
	return p.HasNext
}

func (p *PaginationMeta) GetHasPrev() (v bool) {
	return p.HasPrev
}
func (p *PaginationMeta) SetPage(val int32) {
	p.Page = val
}
func (p *PaginationMeta) SetPageSize(val int32) {
	p.PageSize = val
}
func (p *PaginationMeta) SetTotalItems(val int32) {
	p.TotalItems = val
}
func (p *PaginationMeta) SetTotalPages(val int32) {
	p.TotalPages = val
}
func (p *PaginationMeta) SetHasNext(val bool) {
	p.HasNext = val
}
func (p *PaginationMeta) SetHasPrev(val bool) {
	p.HasPrev = val
}

func (p *PaginationMeta) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("PaginationMeta(%+v)", *p)
}

var fieldIDToName_PaginationMeta = map[int16]string{
	1: "Page",
	2: "PageSize",
	3: "TotalItems",
	4: "TotalPages",
	5: "HasNext",
	6: "HasPrev",
}

type ListPostsRequest struct {
	Base       *base.Base  `thrift:"Base,1" frugal:"1,default,base.Base" json:"Base"`
	Filter     *PostFilter `thrift:"Filter,2,optional" frugal:"2,optional,PostFilter" json:"Filter,omitempty"`
	Pagination *Pagination `thrift:"Pagination,3,optional" frugal:"3,optional,Pagination" json:"Pagination,omitempty"`
}

func NewListPostsRequest() *ListPostsRequest {
	return &ListPostsRequest{}
}

func (p *ListPostsRequest) InitDefault() {
}

var ListPostsRequest_Base_DEFAULT *base.Base

func (p *ListPostsRequest) GetBase() (v *base.Base) {
	if !p.IsSetBase() {
		return ListPostsRequest_Base_DEFAULT
	}
	return p.Base
}

var ListPostsRequest_Filter_DEFAULT *PostFilter

func (p *ListPostsRequest) GetFilter() (v *PostFilter) {
	if !p.IsSetFilter() {
		return ListPostsRequest_Filter_DEFAULT
	}
	return p.Filter
}

var ListPostsRequest_Pagination_DEFAULT *Pagination

func (p *ListPostsRequest) GetPagination() (v *Pagination) {
	if !p.IsSetPagination() {
		return ListPostsRequest_Pagination_DEFAULT
	}
	return p.Pagination
}
func (p *ListPostsRequest) SetBase(val *base.Base) {
	p.Base = val
}
func (p *ListPostsRequest) SetFilter(val *PostFilter) {
	p.Filter = val
}
func (p *ListPostsRequest) SetPagination(val *Pagination) {
	p.Pagination = val
}

func (p *ListPostsRequest) IsSetBase() bool {
	return p.Base != nil
}

func (p *ListPostsRequest) IsSetFilter() bool {
	return p.Filter != nil
}

func (p *ListPostsRequest) IsSetPagination() bool {
	return p.Pagination != nil
}

func (p *ListPostsRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ListPostsRequest(%+v)", *p)
}

var fieldIDToName_ListPostsRequest = map[int16]string{
	1: "Base",
	2: "Filter",
	3: "Pagination",
}

type ListPostsResponse struct {
	Posts      []*Post         `thrift:"Posts,1" frugal:"1,default,list<Post>" json:"Posts"`
	Pagination *PaginationMeta `thrift:"Pagination,2" frugal:"2,default,PaginationMeta" json:"Pagination"`
	BaseResp   *base.BaseResp  `thrift:"BaseResp,255" frugal:"255,default,base.BaseResp" json:"BaseResp"`
}

func NewListPostsResponse() *ListPostsResponse {
	return &ListPostsResponse{}
}

func (p *ListPostsResponse) InitDefault() {
}

func (p *ListPostsResponse) GetPosts() (v []*Post) {
	return p.Posts
}

var ListPostsResponse_Pagination_DEFAULT *PaginationMeta

func (p *ListPostsResponse) GetPagination() (v *PaginationMeta) {
	if !p.IsSetPagination() {
		return ListPostsResponse_Pagination_DEFAULT
	}
	return p.Pagination
}

var ListPostsResponse_BaseResp_DEFAULT *base.BaseResp

func (p *ListPostsResponse) GetBaseResp() (v *base.BaseResp) {
	if !p.IsSetBaseResp() {
		return ListPostsResponse_BaseResp_DEFAULT
	}
	return p.BaseResp
}
func (p *ListPostsResponse) SetPosts(val []*Post) {
	p.Posts = val
}
func (p *ListPostsResponse) SetPagination(val *PaginationMeta) {
	p.Pagination = val
}
func (p *ListPostsResponse) SetBaseResp(val *base.BaseResp) {
	p.BaseResp = val
}

func (p *ListPostsResponse) IsSetPagination() bool {
	return p.Pagination != nil
}

func (p *ListPostsResponse) IsSetBaseResp() bool {
	return p.BaseResp != nil
}

func (p *ListPostsResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ListPostsResponse(%+v)", *p)
}

var fieldIDToName_ListPostsResponse = map[int16]string{
	1:   "Posts",
	2:   "Pagination",
	255: "BaseResp",
}

type GetPostRequest struct {
	Base *base.Base `thrift:"Base,1" frugal:"1,default,base.Base" json:"Base"`
	Id   int64      `thrift:"Id,2" frugal:"2,default,i64" json:"Id"`
}

func NewGetPostRequest() *GetPostRequest {
	return &GetPostRequest{}
}

func (p *GetPostRequest) InitDefault() {
}

var GetPostRequest_Base_DEFAULT *base.Base

func (p *GetPostRequest) GetBase() (v *base.Base) {
	if !p.IsSetBase() {
		return GetPostRequest_Base_DEFAULT
	}
	return p.Base
}

func (p *GetPostRequest) GetId() (v int64) {
	return p.Id
}
func (p *GetPostRequest) SetBase(val *base.Base) {
	p.Base = val
}
func (p *GetPostRequest) SetId(val int64) {
	p.Id = val
}

func (p *GetPostRequest) IsSetBase() bool {
	return p.Base != nil
}

func (p *GetPostRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetPostRequest(%+v)", *p)
}

var fieldIDToName_GetPostRequest = map[int16]string{
	1: "Base",
	2: "Id",
}

type GetPostResponse struct {
	Post     *Post          `thrift:"Post,1" frugal:"1,default,Post" json:"Post"`
	BaseResp *base.BaseResp `thrift:"BaseResp,255" frugal:"255,default,base.BaseResp" json:"BaseResp"`
}

func NewGetPostResponse() *GetPostResponse {
	return &GetPostResponse{}
}

func (p *GetPostResponse) InitDefault() {
}

var GetPostResponse_Post_DEFAULT *Post

func (p *GetPostResponse) GetPost() (v *Post) {
	if !p.IsSetPost() {
		return GetPostResponse_Post_DEFAULT
	}
	return p.Post
}

var GetPostResponse_BaseResp_DEFAULT *base.BaseResp

func (p *GetPostResponse) GetBaseResp() (v *base.BaseResp) {
	if !p.IsSetBaseResp() {
		return GetPostResponse_BaseResp_DEFAULT
	}
	return p.BaseResp
}
func (p *GetPostResponse) SetPost(val *Post) {
	p.Post = val
}
func (p *GetPostResponse) SetBaseResp(val *base.BaseResp) {
	p.BaseResp = val
}

func (p *GetPostResponse) IsSetPost() bool {
	return p.Post != nil
}

func (p *GetPostResponse) IsSetBaseResp() bool {
	return p.BaseResp != nil
}

func (p *GetPostResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetPostResponse(%+v)", *p)
}

var fieldIDToName_GetPostResponse = map[int16]string{
	1:   "Post",
	255: "BaseResp",
}

type CreatePostRequest struct {
	Base   *base.Base `thrift:"Base,1" frugal:"1,default,base.Base" json:"Base"`
	UserId int64      `thrift:"UserId,2" frugal:"2,default,i64" json:"UserId"`
	Title  string     `thrift:"Title,3" frugal:"3,default,string" json:"Title"`
	Body   string     `thrift:"Body,4" frugal:"4,default,string" json:"Body"`
}

func NewCreatePostRequest() *CreatePostRequest {
	return &CreatePostRequest{}
}

func (p *CreatePostRequest) InitDefault() {
}

var CreatePostRequest_Base_DEFAULT *base.Base

func (p *CreatePostRequest) GetBase() (v *base.Base) {
	if !p.IsSetBase() {
		return CreatePostRequest_Base_DEFAULT
	}
	return p.Base
}

func (p *CreatePostRequest) GetUserId() (v int64) {
	return p.UserId
}

func (p *CreatePostRequest) GetTitle() (v string) {
	return p.Title
}

func (p *CreatePostRequest) GetBody() (v string) {
	return p.Body
}
func (p *CreatePostRequest) SetBase(val *base.Base) {
	p.Base = val
}
func (p *CreatePostRequest) SetUserId(val int64) {
	p.UserId = val
}
func (p *CreatePostRequest) SetTitle(val string) {
	p.Title = val
}
func (p *CreatePostRequest) SetBody(val string) {
	p.Body = val
}

func (p *CreatePostRequest) IsSetBase() bool {
	return p.Base != nil
}

func (p *CreatePostRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("CreatePostRequest(%+v)", *p)
}

var fieldIDToName_CreatePostRequest = map[int16]string{
	1: "Base",
	2: "UserId",
	3: "Title",
	4: "Body",
}

type CreatePostResponse struct {
	Post     *Post          `thrift:"Post,1" frugal:"1,default,Post" json:"Post"`
	BaseResp *base.BaseResp `thrift:"BaseResp,255" frugal:"255,default,base.BaseResp" json:"BaseResp"`
}

func NewCreatePostResponse() *CreatePostResponse {
	return &CreatePostResponse{}
}

func (p *CreatePostResponse) InitDefault() {
}

var CreatePostResponse_Post_DEFAULT *Post

func (p *CreatePostResponse) GetPost() (v *Post) {
	if !p.IsSetPost() {
		return CreatePostResponse_Post_DEFAULT
	}
	return p.Post
}

var CreatePostResponse_BaseResp_DEFAULT *base.BaseResp

func (p *CreatePostResponse) GetBaseResp() (v *base.BaseResp) {
	if !p.IsSetBaseResp() {
		return CreatePostResponse_BaseResp_DEFAULT
	}
	return p.BaseResp
}
func (p *CreatePostResponse) SetPost(val *Post) {
	p.Post = val
}
func (p *CreatePostResponse) SetBaseResp(val *base.BaseResp) {
	p.BaseResp = val
}

func (p *CreatePostResponse) IsSetPost() bool {
	return p.Post != nil
}

func (p *CreatePostResponse) IsSetBaseResp() bool {
	return p.BaseResp != nil
}

func (p *CreatePostResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("CreatePostResponse(%+v)", *p)
}

var fieldIDToName_CreatePostResponse = map[int16]string{
	1:   "Post",
	255: "BaseResp",
}

type UpdatePostRequest struct {
	Base  *base.Base `thrift:"Base,1" frugal:"1,default,base.Base" json:"Base"`
	Id    int64      `thrift:"Id,2" frugal:"2,default,i64" json:"Id"`
	Title *string    `thrift:"Title,3,optional" frugal:"3,optional,string" json:"Title,omitempty"`
	Body  *string    `thrift:"Body,4,optional" frugal:"4,optional,string" json:"Body,omitempty"`
}

func NewUpdatePostRequest() *UpdatePostRequest {
	return &UpdatePostRequest{}
}

func (p *UpdatePostRequest) InitDefault() {
}

var UpdatePostRequest_Base_DEFAULT *base.Base

func (p *UpdatePostRequest) GetBase() (v *base.Base) {
	if !p.IsSetBase() {
		return UpdatePostRequest_Base_DEFAULT
	}
	return p.Base
}

func (p *UpdatePostRequest) GetId() (v int64) {
	return p.Id
}

var UpdatePostRequest_Title_DEFAULT string

func (p *UpdatePostRequest) GetTitle() (v string) {
	if !p.IsSetTitle() {
		return UpdatePostRequest_Title_DEFAULT
	}
	return *p.Title
}

var UpdatePostRequest_Body_DEFAULT string

func (p *UpdatePostRequest) GetBody() (v string) {
	if !p.IsSetBody() {
		return UpdatePostRequest_Body_DEFAULT
	}
	return *p.Body
}
func (p *UpdatePostRequest) SetBase(val *base.Base) {
	p.Base = val
}
func (p *UpdatePostRequest) SetId(val int64) {
	p.Id = val
}
func (p *UpdatePostRequest) SetTitle(val *string) {
	p.Title = val
}
func (p *UpdatePostRequest) SetBody(val *string) {
	p.Body = val
}

func (p *UpdatePostRequest) IsSetBase() bool {
	return p.Base != nil
}

func (p *UpdatePostRequest) IsSetTitle() bool {
	return p.Title != nil
}

func (p *UpdatePostRequest) IsSetBody() bool {
	return p.Body != nil
}

func (p *UpdatePostRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UpdatePostRequest(%+v)", *p)
}

var fieldIDToName_UpdatePostRequest = map[int16]string{
	1: "Base",
	2: "Id",
	3: "Title",
	4: "Body",
}

type UpdatePostResponse struct {
	Post     *Post          `thrift:"Post,1" frugal:"1,default,Post" json:"Post"`
	BaseResp *base.BaseResp `thrift:"BaseResp,255" frugal:"255,default,base.BaseResp" json:"BaseResp"`
}

func NewUpdatePostResponse() *UpdatePostResponse {
	return &UpdatePostResponse{}
}

func (p *UpdatePostResponse) InitDefault() {
}

var UpdatePostResponse_Post_DEFAULT *Post

func (p *UpdatePostResponse) GetPost() (v *Post) {
	if !p.IsSetPost() {
		return UpdatePostResponse_Post_DEFAULT
	}
	return p.Post
}

var UpdatePostResponse_BaseResp_DEFAULT *base.BaseResp

func (p *UpdatePostResponse) GetBaseResp() (v *base.BaseResp) {
	if !p.IsSetBaseResp() {
		return UpdatePostResponse_BaseResp_DEFAULT
	}
	return p.BaseResp
}
func (p *UpdatePostResponse) SetPost(val *Post) {
	p.Post = val
}
func (p *UpdatePostResponse) SetBaseResp(val *base.BaseResp) {
	p.BaseResp = val
}

func (p *UpdatePostResponse) IsSetPost() bool {
	return p.Post != nil
}

func (p *UpdatePostResponse) IsSetBaseResp() bool {
	return p.BaseResp != nil
}

func (p *UpdatePostResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UpdatePostResponse(%+v)", *p)
}

var fieldIDToName_UpdatePostResponse = map[int16]string{
	1:   "Post",
	255: "BaseResp",
}

type DeletePostRequest struct {
	Base *base.Base `thrift:"Base,1" frugal:"1,default,base.Base" json:"Base"`
	Id   int64      `thrift:"Id,2" frugal:"2,default,i64" json:"Id"`
}

func NewDeletePostRequest() *DeletePostRequest {
	return &DeletePostRequest{}
}

func (p *DeletePostRequest) InitDefault() {
}

var DeletePostRequest_Base_DEFAULT *base.Base

func (p *DeletePostRequest) GetBase() (v *base.Base) {
	if !p.IsSetBase() {
		return DeletePostRequest_Base_DEFAULT
	}
	return p.Base
}

func (p *DeletePostRequest) GetId() (v int64) {
	return p.Id
}
func (p *DeletePostRequest) SetBase(val *base.Base) {
	p.Base = val
}
func (p *DeletePostRequest) SetId(val int64) {
	p.Id = val
}

func (p *DeletePostRequest) IsSetBase() bool {
	return p.Base != nil
}

func (p *DeletePostRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("DeletePostRequest(%+v)", *p)
}

var fieldIDToName_DeletePostRequest = map[int16]string{
	1: "Base",
	2: "Id",
}

type DeletePostResponse struct {
	BaseResp *base.BaseResp `thrift:"BaseResp,255" frugal:"255,default,base.BaseResp" json:"BaseResp"`
}

func NewDeletePostResponse() *DeletePostResponse {
	return &DeletePostResponse{}
}

func (p *DeletePostResponse) InitDefault() {
}

var DeletePostResponse_BaseResp_DEFAULT *base.BaseResp

func (p *DeletePostResponse) GetBaseResp() (v *base.BaseResp) {
	if !p.IsSetBaseResp() {
		return DeletePostResponse_BaseResp_DEFAULT
	}
	return p.BaseResp
}
func (p *DeletePostResponse) SetBaseResp(val *base.BaseResp) {
	p.BaseResp = val
}

func (p *DeletePostResponse) IsSetBaseResp() bool {
	return p.BaseResp != nil
}

func (p *DeletePostResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("DeletePostResponse(%+v)", *p)
}

var fieldIDToName_DeletePostResponse = map[int16]string{
	255: "BaseResp",
}

type BatchCreatePostsRequest struct {
	Base  *base.Base           `thrift:"Base,1" frugal:"1,default,base.Base" json:"Base"`
	Posts []*CreatePostRequest `thrift:"Posts,2" frugal:"2,default,list<CreatePostRequest>" json:"Posts"`
}

func NewBatchCreatePostsRequest() *BatchCreatePostsRequest {
	return &BatchCreatePostsRequest{}
}

func (p *BatchCreatePostsRequest) InitDefault() {
}

var BatchCreatePostsRequest_Base_DEFAULT *base.Base

func (p *BatchCreatePostsRequest) GetBase() (v *base.Base) {
	if !p.IsSetBase() {
		return BatchCreatePostsRequest_Base_DEFAULT
	}
	return p.Base
}

func (p *BatchCreatePostsRequest) GetPosts() (v []*CreatePostRequest) {
	return p.Posts
}
func (p *BatchCreatePostsRequest) SetBase(val *base.Base) {
	p.Base = val
}
func (p *BatchCreatePostsRequest) SetPosts(val []*CreatePostRequest) {
	p.Posts = val
}

func (p *BatchCreatePostsRequest) IsSetBase() bool {
	return p.Base != nil
}

func (p *BatchCreatePostsRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("BatchCreatePostsRequest(%+v)", *p)
}

var fieldIDToName_BatchCreatePostsRequest = map[int16]string{
	1: "Base",
	2: "Posts",
}

type BatchCreatePostsResponse struct {
	Created  int32          `thrift:"Created,1" frugal:"1,default,i32" json:"Created"`
	Failed   int32          `thrift:"Failed,2" frugal:"2,default,i32" json:"Failed"`
	Errors   []string       `thrift:"Errors,3" frugal:"3,default,list<string>" json:"Errors"`
	PostIds  []int64        `thrift:"PostIds,4" frugal:"4,default,list<i64>" json:"PostIds"`
	BaseResp *base.BaseResp `thrift:"BaseResp,255" frugal:"255,default,base.BaseResp" json:"BaseResp"`
}

func NewBatchCreatePostsResponse() *BatchCreatePostsResponse {
	return &BatchCreatePostsResponse{}
}

func (p *BatchCreatePostsResponse) InitDefault() {
}

func (p *BatchCreatePostsResponse) GetCreated() (v int32) {
	return p.Created
}

func (p *BatchCreatePostsResponse) GetFailed() (v int32) {
	return p.Failed
}

func (p *BatchCreatePostsResponse) GetErrors() (v []string) {
	return p.Errors
}

func (p *BatchCreatePostsResponse) GetPostIds() (v []int64) {
	return p.PostIds
}

var BatchCreatePostsResponse_BaseResp_DEFAULT *base.BaseResp

func (p *BatchCreatePostsResponse) GetBaseResp() (v *base.BaseResp) {
	if !p.IsSetBaseResp() {
		return BatchCreatePostsResponse_BaseResp_DEFAULT
	}
	return p.BaseResp
}
func (p *BatchCreatePostsResponse) SetCreated(val int32) {
	p.Created = val
}
func (p *BatchCreatePostsResponse) SetFailed(val int32) {
	p.Failed = val
}
func (p *BatchCreatePostsResponse) SetErrors(val []string) {
	p.Errors = val
}
func (p *BatchCreatePostsResponse) SetPostIds(val []int64) {
	p.PostIds = val
}
func (p *BatchCreatePostsResponse) SetBaseResp(val *base.BaseResp) {
	p.BaseResp = val
}

func (p *BatchCreatePostsResponse) IsSetBaseResp() bool {
	return p.BaseResp != nil
}

func (p *BatchCreatePostsResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("BatchCreatePostsResponse(%+v)", *p)
}

var fieldIDToName_BatchCreatePostsResponse = map[int16]string{
	1:   "Created",
	2:   "Failed",
	3:   "Errors",
	4:   "PostIds",
	255: "BaseResp",
}

type CharacterStat struct {
	Character string  `thrift:"Character,1" frugal:"1,default,string" json:"Character"`
	Count     int64   `thrift:"Count,2" frugal:"2,default,i64" json:"Count"`
	Frequency float64 `thrift:"Frequency,3" frugal:"3,default,double" json:"Frequency"`
}

func NewCharacterStat() *CharacterStat {
	return &CharacterStat{}
}

func (p *CharacterStat) InitDefault() {
}

func (p *CharacterStat) GetCharacter() (v string) {
	return p.Character
}

func (p *CharacterStat) GetCount() (v int64) {
	return p.Count
}

func (p *CharacterStat) GetFrequency() (v float64) {
	return p.Frequency
}
func (p *CharacterStat) SetCharacter(val string) {
	p.Character = val
}
func (p *CharacterStat) SetCount(val int64) {
	p.Count = val
}
func (p *CharacterStat) SetFrequency(val float64) {
	p.Frequency = val
}

func (p *CharacterStat) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("CharacterStat(%+v)", *p)
}

var fieldIDToName_CharacterStat = map[int16]string{
	1: "Character",
	2: "Count",
	3: "Frequency",
}

type AnalyticsStats struct {
	AveragePostLength float64          `thrift:"AveragePostLength,1" frugal:"1,default,double" json:"AveragePostLength"`
	MedianPostLength  int32            `thrift:"MedianPostLength,2" frugal:"2,default,i32" json:"MedianPostLength"`
	PostsPerUser      map[int64]int32  `thrift:"PostsPerUser,3" frugal:"3,default,map<i64:i32>" json:"PostsPerUser"`
	TimeDistribution  map[string]int32 `thrift:"TimeDistribution,4" frugal:"4,default,map<string:i32>" json:"TimeDistribution"`
}

func NewAnalyticsStats() *AnalyticsStats {
	return &AnalyticsStats{}
}

func (p *AnalyticsStats) InitDefault() {
}

func (p *AnalyticsStats) GetAveragePostLength() (v float64) {
	return p.AveragePostLength
}

func (p *AnalyticsStats) GetMedianPostLength() (v int32) {
	return p.MedianPostLength
}

func (p *AnalyticsStats) GetPostsPerUser() (v map[int64]int32) {
	return p.PostsPerUser
}

func (p *AnalyticsStats) GetTimeDistribution() (v map[string]int32) {
	return p.TimeDistribution
}
func (p *AnalyticsStats) SetAveragePostLength(val float64) {
	p.AveragePostLength = val
}
func (p *AnalyticsStats) SetMedianPostLength(val int32) {
	p.MedianPostLength = val
}
func (p *AnalyticsStats) SetPostsPerUser(val map[int64]int32) {
	p.PostsPerUser = val
}
func (p *AnalyticsStats) SetTimeDistribution(val map[string]int32) {
	p.TimeDistribution = val
}

func (p *AnalyticsStats) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("AnalyticsStats(%+v)", *p)
}

var fieldIDToName_AnalyticsStats = map[int16]string{
	1: "AveragePostLength",
	2: "MedianPostLength",
	3: "PostsPerUser",
	4: "TimeDistribution",
}

type AnalyzePostsRequest struct {
	Base *base.Base `thrift:"Base,1" frugal:"1,default,base.Base" json:"Base"`
}

func NewAnalyzePostsRequest() *AnalyzePostsRequest {
	return &AnalyzePostsRequest{}
}

func (p *AnalyzePostsRequest) InitDefault() {
}

var AnalyzePostsRequest_Base_DEFAULT *base.Base

func (p *AnalyzePostsRequest) GetBase() (v *base.Base) {
	if !p.IsSetBase() {
		return AnalyzePostsRequest_Base_DEFAULT
	}
	return p.Base
}
func (p *AnalyzePostsRequest) SetBase(val *base.Base) {
	p.Base = val
}

func (p *AnalyzePostsRequest) IsSetBase() bool {
	return p.Base != nil
}

func (p *AnalyzePostsRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("AnalyzePostsRequest(%+v)", *p)
}

var fieldIDToName_AnalyzePostsRequest = map[int16]string{
	1: "Base",
}

type AnalyzePostsResponse struct {
	TotalPosts      int32            `thrift:"TotalPosts,1" frugal:"1,default,i32" json:"TotalPosts"`
	TotalCharacters int64            `thrift:"TotalCharacters,2" frugal:"2,default,i64" json:"TotalCharacters"`
	UniqueChars     int32            `thrift:"UniqueChars,3" frugal:"3,default,i32" json:"UniqueChars"`
	TopCharacters   []*CharacterStat `thrift:"TopCharacters,4" frugal:"4,default,list<CharacterStat>" json:"TopCharacters"`
	Statistics      *AnalyticsStats  `thrift:"Statistics,5" frugal:"5,default,AnalyticsStats" json:"Statistics"`
	BaseResp        *base.BaseResp   `thrift:"BaseResp,255" frugal:"255,default,base.BaseResp" json:"BaseResp"`
}

func NewAnalyzePostsResponse() *AnalyzePostsResponse {
	return &AnalyzePostsResponse{}
}

func (p *AnalyzePostsResponse) InitDefault() {
}

func (p *AnalyzePostsResponse) GetTotalPosts() (v int32) {
	return p.TotalPosts
}

func (p *AnalyzePostsResponse) GetTotalCharacters() (v int64) {
	return p.TotalCharacters
}

func (p *AnalyzePostsResponse) GetUniqueChars() (v int32) {
	return p.UniqueChars
}

func (p *AnalyzePostsResponse) GetTopCharacters() (v []*CharacterStat) {
	return p.TopCharacters
}

var AnalyzePostsResponse_Statistics_DEFAULT *AnalyticsStats

func (p *AnalyzePostsResponse) GetStatistics() (v *AnalyticsStats) {
	if !p.IsSetStatistics() {
		return AnalyzePostsResponse_Statistics_DEFAULT
	}
	return p.Statistics
}

var AnalyzePostsResponse_BaseResp_DEFAULT *base.BaseResp

func (p *AnalyzePostsResponse) GetBaseResp() (v *base.BaseResp) {
	if !p.IsSetBaseResp() {
		return AnalyzePostsResponse_BaseResp_DEFAULT
	}
	return p.BaseResp
}
func (p *AnalyzePostsResponse) SetTotalPosts(val int32) {
	p.TotalPosts = val
}
func (p *AnalyzePostsResponse) SetTotalCharacters(val int64) {
	p.TotalCharacters = val
}
func (p *AnalyzePostsResponse) SetUniqueChars(val int32) {
	p.UniqueChars = val
}
func (p *AnalyzePostsResponse) SetTopCharacters(val []*CharacterStat) {
	p.TopCharacters = val
}
func (p *AnalyzePostsResponse) SetStatistics(val *AnalyticsStats) {
	p.Statistics = val
}
func (p *AnalyzePostsResponse) SetBaseResp(val *base.BaseResp) {
	p.BaseResp = val
}

func (p *AnalyzePostsResponse) IsSetStatistics() bool {
	return p.Statistics != nil
}

func (p *AnalyzePostsResponse) IsSetBaseResp() bool {
	return p.BaseResp != nil
}

func (p *AnalyzePostsResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("AnalyzePostsResponse(%+v)", *p)
}

var fieldIDToName_AnalyzePostsResponse = map[int16]string{
	1:   "TotalPosts",
	2:   "TotalCharacters",
	3:   "UniqueChars",
	4:   "TopCharacters",
	5:   "Statistics",
	255: "BaseResp",
}

type PostService interface {
	ListPosts(ctx context.Context, req *ListPostsRequest) (r *ListPostsResponse, err error)

	GetPost(ctx context.Context, req *GetPostRequest) (r *GetPostResponse, err error)

	CreatePost(ctx context.Context, req *CreatePostRequest) (r *CreatePostResponse, err error)

	UpdatePost(ctx context.Context, req *UpdatePostRequest) (r *UpdatePostResponse, err error)

	DeletePost(ctx context.Context, req *DeletePostRequest) (r *DeletePostResponse, err error)

	BatchCreatePosts(ctx context.Context, req *BatchCreatePostsRequest) (r *BatchCreatePostsResponse, err error)

	AnalyzePosts(ctx context.Context, req *AnalyzePostsRequest) (r *AnalyzePostsResponse, err error)
}

type PostServiceListPostsArgs struct {
	Req *ListPostsRequest `thrift:"req,1" frugal:"1,default,ListPostsRequest" json:"req"`
}

func NewPostServiceListPostsArgs() *PostServiceListPostsArgs {
	return &PostServiceListPostsArgs{}
}

func (p *PostServiceListPostsArgs) InitDefault() {
}

var PostServiceListPostsArgs_Req_DEFAULT *ListPostsRequest

func (p *PostServiceListPostsArgs) GetReq() (v *ListPostsRequest) {
	if !p.IsSetReq() {
		return PostServiceListPostsArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *PostServiceListPostsArgs) SetReq(val *ListPostsRequest) {
	p.Req = val
}

func (p *PostServiceListPostsArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *PostServiceListPostsArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("PostServiceListPostsArgs(%+v)", *p)
}

var fieldIDToName_PostServiceListPostsArgs = map[int16]string{
	1: "req",
}

type PostServiceListPostsResult struct {
	Success *ListPostsResponse `thrift:"success,0,optional" frugal:"0,optional,ListPostsResponse" json:"success,omitempty"`
}

func NewPostServiceListPostsResult() *PostServiceListPostsResult {
	return &PostServiceListPostsResult{}
}

func (p *PostServiceListPostsResult) InitDefault() {
}

var PostServiceListPostsResult_Success_DEFAULT *ListPostsResponse

func (p *PostServiceListPostsResult) GetSuccess() (v *ListPostsResponse) {
	if !p.IsSetSuccess() {
		return PostServiceListPostsResult_Success_DEFAULT
	}
	return p.Success
}
func (p *PostServiceListPostsResult) SetSuccess(x interface{}) {
	p.Success = x.(*ListPostsResponse)
}

func (p *PostServiceListPostsResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *PostServiceListPostsResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("PostServiceListPostsResult(%+v)", *p)
}

var fieldIDToName_PostServiceListPostsResult = map[int16]string{
	0: "success",
}

type PostServiceGetPostArgs struct {
	Req *GetPostRequest `thrift:"req,1" frugal:"1,default,GetPostRequest" json:"req"`
}

func NewPostServiceGetPostArgs() *PostServiceGetPostArgs {
	return &PostServiceGetPostArgs{}
}

func (p *PostServiceGetPostArgs) InitDefault() {
}

var PostServiceGetPostArgs_Req_DEFAULT *GetPostRequest

func (p *PostServiceGetPostArgs) GetReq() (v *GetPostRequest) {
	if !p.IsSetReq() {
		return PostServiceGetPostArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *PostServiceGetPostArgs) SetReq(val *GetPostRequest) {
	p.Req = val
}

func (p *PostServiceGetPostArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *PostServiceGetPostArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("PostServiceGetPostArgs(%+v)", *p)
}

var fieldIDToName_PostServiceGetPostArgs = map[int16]string{
	1: "req",
}

type PostServiceGetPostResult struct {
	Success *GetPostResponse `thrift:"success,0,optional" frugal:"0,optional,GetPostResponse" json:"success,omitempty"`
}

func NewPostServiceGetPostResult() *PostServiceGetPostResult {
	return &PostServiceGetPostResult{}
}

func (p *PostServiceGetPostResult) InitDefault() {
}

var PostServiceGetPostResult_Success_DEFAULT *GetPostResponse

func (p *PostServiceGetPostResult) GetSuccess() (v *GetPostResponse) {
	if !p.IsSetSuccess() {
		return PostServiceGetPostResult_Success_DEFAULT
	}
	return p.Success
}
func (p *PostServiceGetPostResult) SetSuccess(x interface{}) {
	p.Success = x.(*GetPostResponse)
}

func (p *PostServiceGetPostResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *PostServiceGetPostResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("PostServiceGetPostResult(%+v)", *p)
}

var fieldIDToName_PostServiceGetPostResult = map[int16]string{
	0: "success",
}

type PostServiceCreatePostArgs struct {
	Req *CreatePostRequest `thrift:"req,1" frugal:"1,default,CreatePostRequest" json:"req"`
}

func NewPostServiceCreatePostArgs() *PostServiceCreatePostArgs {
	return &PostServiceCreatePostArgs{}
}

func (p *PostServiceCreatePostArgs) InitDefault() {
}

var PostServiceCreatePostArgs_Req_DEFAULT *CreatePostRequest

func (p *PostServiceCreatePostArgs) GetReq() (v *CreatePostRequest) {
	if !p.IsSetReq() {
		return PostServiceCreatePostArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *PostServiceCreatePostArgs) SetReq(val *CreatePostRequest) {
	p.Req = val
}

func (p *PostServiceCreatePostArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *PostServiceCreatePostArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("PostServiceCreatePostArgs(%+v)", *p)
}

var fieldIDToName_PostServiceCreatePostArgs = map[int16]string{
	1: "req",
}

type PostServiceCreatePostResult struct {
	Success *CreatePostResponse `thrift:"success,0,optional" frugal:"0,optional,CreatePostResponse" json:"success,omitempty"`
}

func NewPostServiceCreatePostResult() *PostServiceCreatePostResult {
	return &PostServiceCreatePostResult{}
}

func (p *PostServiceCreatePostResult) InitDefault() {
}

var PostServiceCreatePostResult_Success_DEFAULT *CreatePostResponse

func (p *PostServiceCreatePostResult) GetSuccess() (v *CreatePostResponse) {
	if !p.IsSetSuccess() {
		return PostServiceCreatePostResult_Success_DEFAULT
	}
	return p.Success
}
func (p *PostServiceCreatePostResult) SetSuccess(x interface{}) {
	p.Success = x.(*CreatePostResponse)
}

func (p *PostServiceCreatePostResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *PostServiceCreatePostResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("PostServiceCreatePostResult(%+v)", *p)
}

var fieldIDToName_PostServiceCreatePostResult = map[int16]string{
	0: "success",
}

type PostServiceUpdatePostArgs struct {
	Req *UpdatePostRequest `thrift:"req,1" frugal:"1,default,UpdatePostRequest" json:"req"`
}

func NewPostServiceUpdatePostArgs() *PostServiceUpdatePostArgs {
	return &PostServiceUpdatePostArgs{}
}

func (p *PostServiceUpdatePostArgs) InitDefault() {
}

var PostServiceUpdatePostArgs_Req_DEFAULT *UpdatePostRequest

func (p *PostServiceUpdatePostArgs) GetReq() (v *UpdatePostRequest) {
	if !p.IsSetReq() {
		return PostServiceUpdatePostArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *PostServiceUpdatePostArgs) SetReq(val *UpdatePostRequest) {
	p.Req = val
}

func (p *PostServiceUpdatePostArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *PostServiceUpdatePostArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("PostServiceUpdatePostArgs(%+v)", *p)
}

var fieldIDToName_PostServiceUpdatePostArgs = map[int16]string{
	1: "req",
}

type PostServiceUpdatePostResult struct {
	Success *UpdatePostResponse `thrift:"success,0,optional" frugal:"0,optional,UpdatePostResponse" json:"success,omitempty"`
}

func NewPostServiceUpdatePostResult() *PostServiceUpdatePostResult {
	return &PostServiceUpdatePostResult{}
}

func (p *PostServiceUpdatePostResult) InitDefault() {
}

var PostServiceUpdatePostResult_Success_DEFAULT *UpdatePostResponse

func (p *PostServiceUpdatePostResult) GetSuccess() (v *UpdatePostResponse) {
	if !p.IsSetSuccess() {
		return PostServiceUpdatePostResult_Success_DEFAULT
	}
	return p.Success
}
func (p *PostServiceUpdatePostResult) SetSuccess(x interface{}) {
	p.Success = x.(*UpdatePostResponse)
}

func (p *PostServiceUpdatePostResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *PostServiceUpdatePostResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("PostServiceUpdatePostResult(%+v)", *p)
}

var fieldIDToName_PostServiceUpdatePostResult = map[int16]string{
	0: "success",
}

type PostServiceDeletePostArgs struct {
	Req *DeletePostRequest `thrift:"req,1" frugal:"1,default,DeletePostRequest" json:"req"`
}

func NewPostServiceDeletePostArgs() *PostServiceDeletePostArgs {
	return &PostServiceDeletePostArgs{}
}

func (p *PostServiceDeletePostArgs) InitDefault() {
}

var PostServiceDeletePostArgs_Req_DEFAULT *DeletePostRequest

func (p *PostServiceDeletePostArgs) GetReq() (v *DeletePostRequest) {
	if !p.IsSetReq() {
		return PostServiceDeletePostArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *PostServiceDeletePostArgs) SetReq(val *DeletePostRequest) {
	p.Req = val
}

func (p *PostServiceDeletePostArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *PostServiceDeletePostArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("PostServiceDeletePostArgs(%+v)", *p)
}

var fieldIDToName_PostServiceDeletePostArgs = map[int16]string{
	1: "req",
}

type PostServiceDeletePostResult struct {
	Success *DeletePostResponse `thrift:"success,0,optional" frugal:"0,optional,DeletePostResponse" json:"success,omitempty"`
}

func NewPostServiceDeletePostResult() *PostServiceDeletePostResult {
	return &PostServiceDeletePostResult{}
}

func (p *PostServiceDeletePostResult) InitDefault() {
}

var PostServiceDeletePostResult_Success_DEFAULT *DeletePostResponse

func (p *PostServiceDeletePostResult) GetSuccess() (v *DeletePostResponse) {
	if !p.IsSetSuccess() {
		return PostServiceDeletePostResult_Success_DEFAULT
	}
	return p.Success
}
func (p *PostServiceDeletePostResult) SetSuccess(x interface{}) {
	p.Success = x.(*DeletePostResponse)
}

func (p *PostServiceDeletePostResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *PostServiceDeletePostResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("PostServiceDeletePostResult(%+v)", *p)
}

var fieldIDToName_PostServiceDeletePostResult = map[int16]string{
	0: "success",
}

type PostServiceBatchCreatePostsArgs struct {
	Req *BatchCreatePostsRequest `thrift:"req,1" frugal:"1,default,BatchCreatePostsRequest" json:"req"`
}

func NewPostServiceBatchCreatePostsArgs() *PostServiceBatchCreatePostsArgs {
	return &PostServiceBatchCreatePostsArgs{}
}

func (p *PostServiceBatchCreatePostsArgs) InitDefault() {
}

var PostServiceBatchCreatePostsArgs_Req_DEFAULT *BatchCreatePostsRequest

func (p *PostServiceBatchCreatePostsArgs) GetReq() (v *BatchCreatePostsRequest) {
	if !p.IsSetReq() {
		return PostServiceBatchCreatePostsArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *PostServiceBatchCreatePostsArgs) SetReq(val *BatchCreatePostsRequest) {
	p.Req = val
}

func (p *PostServiceBatchCreatePostsArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *PostServiceBatchCreatePostsArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("PostServiceBatchCreatePostsArgs(%+v)", *p)
}

var fieldIDToName_PostServiceBatchCreatePostsArgs = map[int16]string{
	1: "req",
}

type PostServiceBatchCreatePostsResult struct {
	Success *BatchCreatePostsResponse `thrift:"success,0,optional" frugal:"0,optional,BatchCreatePostsResponse" json:"success,omitempty"`
}

func NewPostServiceBatchCreatePostsResult() *PostServiceBatchCreatePostsResult {
	return &PostServiceBatchCreatePostsResult{}
}

func (p *PostServiceBatchCreatePostsResult) InitDefault() {
}

var PostServiceBatchCreatePostsResult_Success_DEFAULT *BatchCreatePostsResponse

func (p *PostServiceBatchCreatePostsResult) GetSuccess() (v *BatchCreatePostsResponse) {
	if !p.IsSetSuccess() {
		return PostServiceBatchCreatePostsResult_Success_DEFAULT
	}
	return p.Success
}
func (p *PostServiceBatchCreatePostsResult) SetSuccess(x interface{}) {
	p.Success = x.(*BatchCreatePostsResponse)
}

func (p *PostServiceBatchCreatePostsResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *PostServiceBatchCreatePostsResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("PostServiceBatchCreatePostsResult(%+v)", *p)
}

var fieldIDToName_PostServiceBatchCreatePostsResult = map[int16]string{
	0: "success",
}

type PostServiceAnalyzePostsArgs struct {
	Req *AnalyzePostsRequest `thrift:"req,1" frugal:"1,default,AnalyzePostsRequest" json:"req"`
}

func NewPostServiceAnalyzePostsArgs() *PostServiceAnalyzePostsArgs {
	return &PostServiceAnalyzePostsArgs{}
}

func (p *PostServiceAnalyzePostsArgs) InitDefault() {
}

var PostServiceAnalyzePostsArgs_Req_DEFAULT *AnalyzePostsRequest

func (p *PostServiceAnalyzePostsArgs) GetReq() (v *AnalyzePostsRequest) {
	if !p.IsSetReq() {
		return PostServiceAnalyzePostsArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *PostServiceAnalyzePostsArgs) SetReq(val *AnalyzePostsRequest) {
	p.Req = val
}

func (p *PostServiceAnalyzePostsArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *PostServiceAnalyzePostsArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("PostServiceAnalyzePostsArgs(%+v)", *p)
}

var fieldIDToName_PostServiceAnalyzePostsArgs = map[int16]string{
	1: "req",
}

type PostServiceAnalyzePostsResult struct {
	Success *AnalyzePostsResponse `thrift:"success,0,optional" frugal:"0,optional,AnalyzePostsResponse" json:"success,omitempty"`
}

func NewPostServiceAnalyzePostsResult() *PostServiceAnalyzePostsResult {
	return &PostServiceAnalyzePostsResult{}
}

func (p *PostServiceAnalyzePostsResult) InitDefault() {
}

var PostServiceAnalyzePostsResult_Success_DEFAULT *AnalyzePostsResponse

func (p *PostServiceAnalyzePostsResult) GetSuccess() (v *AnalyzePostsResponse) {
	if !p.IsSetSuccess() {
		return PostServiceAnalyzePostsResult_Success_DEFAULT
	}
	return p.Success
}
func (p *PostServiceAnalyzePostsResult) SetSuccess(x interface{}) {
	p.Success = x.(*AnalyzePostsResponse)
}

func (p *PostServiceAnalyzePostsResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *PostServiceAnalyzePostsResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("PostServiceAnalyzePostsResult(%+v)", *p)
}

var fieldIDToName_PostServiceAnalyzePostsResult = map[int16]string{
	0: "success",
}
